/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ProfitThePonzi } from "./ProfitThePonzi";

export { ProfitThePonzi__factory } from "./factories/ProfitThePonzi__factory";
